### ISSUE TITLE
Suggestion: use a Redis Hash

### ISSUE THREAD

**Issue by itamarhaber** [anujdas/running_stat#3]
Instead of 3 separate keys for each bucket, just use one key to store a Hash with all fields in it. This has two main advantages:
1. Less footprint - cut down the per key RAM overhead by 66%.
2. Cluster-safer - no chance for CROSSSLOT errors, no need to explicitly use hash tags on bucket's keys

**Comment by anujdas** [comment]
That's a great suggestion, HINCRYBYFLOAT will be good enough to replace INCRBYFLOAT. I'll try it out.
